import PageGreeting from "../../components/page-greeting/pageGreeting";
import {
  PROJECTS_GREETING,
  PROJECTS_SECTION_PORTFOLIO,
  PROJECTS_SECTION_BAYTREE,
  PROJECTS_SECTION_LYRICAL,
  PROJECTS_SECTION_SABS,
  PROJECTS_SECTION_FITCHECK,
  PROJECTS_SECTION_STUDDY_BUDDIES
} from "../../strings";
import Experience from "../../components/experience/experience";

function ProjectsPage() {
  const PROJECTS_TEXT = [
    PROJECTS_GREETING.PROJECTS
  ];

  return (
    <div>
      <PageGreeting
        mainText={PROJECTS_TEXT}
        description={PROJECTS_GREETING.DESCRIPTION}
      />
      <Experience
        title={PROJECTS_SECTION_STUDDY_BUDDIES.NAME}
        subtitle={PROJECTS_SECTION_STUDDY_BUDDIES.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_STUDDY_BUDDIES.DESCRIPTIONS}
        skills={PROJECTS_SECTION_STUDDY_BUDDIES.SKILLS}
        image={PROJECTS_SECTION_STUDDY_BUDDIES.IMAGE_PATH}
        altText={PROJECTS_SECTION_STUDDY_BUDDIES.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_STUDDY_BUDDIES.DATE_RANGE}
      />
      <Experience
        title={PROJECTS_SECTION_PORTFOLIO.NAME}
        subtitle={PROJECTS_SECTION_PORTFOLIO.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_PORTFOLIO.DESCRIPTIONS}
        skills={PROJECTS_SECTION_PORTFOLIO.SKILLS}
        image={PROJECTS_SECTION_PORTFOLIO.IMAGE_PATH}
        altText={PROJECTS_SECTION_PORTFOLIO.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_PORTFOLIO.DATE_RANGE}
      />
      <Experience
        title={PROJECTS_SECTION_BAYTREE.NAME}
        subtitle={PROJECTS_SECTION_BAYTREE.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_BAYTREE.DESCRIPTIONS}
        skills={PROJECTS_SECTION_BAYTREE.SKILLS}
        image={PROJECTS_SECTION_BAYTREE.IMAGE_PATH}
        altText={PROJECTS_SECTION_BAYTREE.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_BAYTREE.DATE_RANGE}
      />
      <Experience
        title={PROJECTS_SECTION_LYRICAL.NAME}
        subtitle={PROJECTS_SECTION_LYRICAL.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_LYRICAL.DESCRIPTIONS}
        skills={PROJECTS_SECTION_LYRICAL.SKILLS}
        image={PROJECTS_SECTION_LYRICAL.IMAGE_PATH}
        altText={PROJECTS_SECTION_LYRICAL.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_LYRICAL.DATE_RANGE}
      />
      <Experience
        title={PROJECTS_SECTION_SABS.NAME}
        subtitle={PROJECTS_SECTION_SABS.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_SABS.DESCRIPTIONS}
        skills={PROJECTS_SECTION_SABS.SKILLS}
        image={PROJECTS_SECTION_SABS.IMAGE_PATH}
        altText={PROJECTS_SECTION_SABS.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_SABS.DATE_RANGE}
      />
      <Experience
        title={PROJECTS_SECTION_FITCHECK.NAME}
        subtitle={PROJECTS_SECTION_FITCHECK.PROJECT_TYPE}
        descriptions={PROJECTS_SECTION_FITCHECK.DESCRIPTIONS}
        skills={PROJECTS_SECTION_FITCHECK.SKILLS}
        image={PROJECTS_SECTION_FITCHECK.IMAGE_PATH}
        altText={PROJECTS_SECTION_FITCHECK.IMAGE_ALT}
        dateRange={PROJECTS_SECTION_FITCHECK.DATE_RANGE}
      />
    </div>
  );
}

export default ProjectsPage;
